name: ShellCheck
on: [push, pull_request]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run ShellCheck
      run: |
        find . -type f -name "*.sh" -exec shellcheck {} \;
